LOAD DATA LOCAL INFILE "D:/Customer.CSV" INTO TABLE customer FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "D:/Product.CSV" INTO TABLE product FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "D:/Stock.CSV" INTO TABLE stock FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "D:/Sales.CSV" INTO TABLE sales FIELDS TERMINATED BY ",";
LOAD DATA LOCAL INFILE "D:/Payment.CSV" INTO TABLE payment FIELDS TERMINATED BY ",";